// Code generated by goctl. DO NOT EDIT.
package types

type AppCountInsert struct {
	Count int64 `json:"count"`
}

type AppCountReply struct {
	Id    int64 `json:"id"`
	AppCounts int64 `json:"appCounts"`
	CreateTime string `json:"creatTime"`
}
