// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"sparkAPPs/api/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/sparkApps/getCount",
				Handler: GetSparkAppCountHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sparkApps/insertCount",
				Handler: InsertSparkAppCountHandler(serverCtx),
			},
		},
	)
}
